### ISSUE TITLE
Official awscrt project now has musllinux wheels in PyPI

### ISSUE THREAD

**Issue by graebm** [qqaatw/aws-crt-python-musllinux#2]
As of awscrt [0.16.21](https://github.com/awslabs/aws-crt-python/releases/tag/v0.16.21), musllinux wheels are uploaded to PyPI

Not sure if you want to deprecate this Github project, or warn people away in the README

Thanks for helping people out with this bridge in the meantime

**Comment by qqaatw** [comment]
Thank you for letting me know! I will add a note in the README.

**Comment by qqaatw** [comment]
Updated the README.
